baseURL = "/"
languageCode = "en"
title = "Chenhao's Blog"
theme = "hugo-nuo"
enableRobotsTXT = true

canonifyurls = true
ignoreFiles = ["_files$", "_cache$"]

# Disqus Username
disqusShortname = "lichenhao"

# Google Analytics UA number
googleAnalytics = "UA-108829179-1"

# Copyright of your post
copyright = "© This site was created with R BlogDown and HuGo by Chenhao Li."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Works"
  weight = 20
  identifier = "works"
  url = "https://github.com/lch14forever"
  
# Add your own params here
[params]
  author = "Chenhao Li (李陈浩)"
  avatar = "/img/avatar.jpg"
  seotitle = "Chenhao's blog posts"
  subtitle = "~ Think as a scientist & Work as an engineer ~"
  description = ""
  paginate = 10

  # Choose your social networks
  email = "lichenhao.sg@gmail.com"
  github = "lch14forever"
  twitter = "li_chenhao"
  linkedin = "chenhao-li-1b695b99"
  #weibo = "weibo_username"
  #wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"

  # Changyan Comments (China Only)
  #changyan = false
  #changyanId = "cyt3toRiB"
  #changyanConf = "prod_0908b1cb9a581501753cce1ed074dbe3"

  # Google Webmaster
  # https://www.google.com/webmasters/
  #googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  #msValidate = "22596E34341DD1D17D6022C44647E587"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  # baiduSiteVerification = "MZ23SPxxfa"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
baiduTongji = "2ed5f50c08edca2c0b923671c4ce2044"

  # ICP Number (China Only)
  # ICP = "苏ICP备16005986号-2"
