---
title: "Frequently Googled Questions"
author: "Chenhao Li （李陈浩）"
categories: ["General"]
tags: ["Bioinformatics", "R", "Linux"]
date: 2018-09-05
output: html_document
summary: "一些从来都需要google的东西"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=FALSE)
```

### Linux

 - Extract (decompress) with a file pattern (wildcard) [ref](https://superuser.com/questions/504798/extract-specific-files-in-a-tar-archive-using-a-wildcard)

```{sh}
tar -xf MyTar.tar --wildcards "*.jpg"
```

### ggplot2

 - rotate axis label [ref](https://stackoverflow.com/questions/1330989/rotating-and-spacing-axis-labels-in-ggplot2)

```{r}
p + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

 - remove legend title [ref](http://www.cookbook-r.com/Graphs/Legends_%28ggplot2%29/#hiding-the-legend-title)

```{r}
# Remove title for fill legend
p + 
  guides(fill=guide_legend(title=NULL))

# Remove title for all legends
p + 
  theme(legend.title=element_blank())
```

 - legends in multiple columns/rows [ref](https://ggplot2.tidyverse.org/reference/guide_legend.html) 
 - A lot of interesting and useful things in this ref
  - overriding the alpha value
  - customizing the legend text angle 
  - etc

```{r}
p + 
  guides(col = guide_legend(nrow = 8))
```